# Adapted from CPython Lib/test/test_string/_support.py
# Upstream: https://github.com/python/cpython/blob/d19de375a204c74ab5f3a28ec42335bae139033d/Lib/test/test_string/_support.py
#
# Auto-generated by scripts/update_upstream_tests.py — do not edit manually.
# To regenerate: python scripts/update_upstream_tests.py --ref d19de375a204c74ab5f3a28ec42335bae139033d

from tstrings import Interpolation

class TStringBaseCase:

    def assertInterpolationEqual(self, i, exp):
        """Test Interpolation equality.

        The *i* argument must be an Interpolation instance.

        The *exp* argument must be a tuple of the form
        (value, expression, conversion, format_spec) where the final three
        items may be omitted and are assumed to be '', None and '' respectively.
        """
        if len(exp) == 4:
            actual = (i.value, i.expression, i.conversion, i.format_spec)
            self.assertEqual(actual, exp)
        elif len(exp) == 3:
            self.assertEqual((i.value, i.expression, i.conversion), exp)
            self.assertEqual(i.format_spec, '')
        elif len(exp) == 2:
            self.assertEqual((i.value, i.expression), exp)
            self.assertEqual(i.conversion, None)
            self.assertEqual(i.format_spec, '')
        elif len(exp) == 1:
            self.assertEqual((i.value,), exp)
            self.assertEqual(i.expression, '')
            self.assertEqual(i.conversion, None)
            self.assertEqual(i.format_spec, '')

    def assertTStringEqual(self, t, strings, interpolations):
        """Test template string literal equality.

        The *strings* argument must be a tuple of strings equal to *t.strings*.

        The *interpolations* argument must be a sequence of tuples which are
        compared against *t.interpolations*. Each tuple must match the form
        described in the `assertInterpolationEqual` method.
        """
        self.assertEqual(t.strings, strings)
        self.assertEqual(len(t.interpolations), len(interpolations))

        # BACKPORT: removed strict=True for Python 3.9 compat
        for i, exp in zip(t.interpolations, interpolations):
            self.assertInterpolationEqual(i, exp)

def convert(value, conversion):
    if conversion == 'a':
        return ascii(value)
    elif conversion == 'r':
        return repr(value)
    elif conversion == 's':
        return str(value)
    return value

def fstring(template):
    parts = []
    # BACKPORT: switched from match-case to if-elif for Python 3.9 compat
    for item in template:
        if isinstance(item, str):
            parts.append(item)
        elif isinstance(item, Interpolation):
            value = convert(item.value, item.conversion)
            value = format(value, item.format_spec)
            parts.append(value)
    return "".join(parts)
