# Adapted from CPython Lib/test/test_string/test_templatelib.py
# Upstream: https://github.com/python/cpython/blob/d19de375a204c74ab5f3a28ec42335bae139033d/Lib/test/test_string/test_templatelib.py
#
# Auto-generated by scripts/update_upstream_tests.py — do not edit manually.
# To regenerate: python scripts/update_upstream_tests.py --ref d19de375a204c74ab5f3a28ec42335bae139033d

import pickle
import unittest
from collections.abc import Iterator, Iterable
from tstrings import Template, Interpolation, t as tst
from _upstream_support import TStringBaseCase, fstring

class TestTemplate(unittest.TestCase, TStringBaseCase):

    def test_common(self):
        self.assertEqual(type(tst('')).__name__, 'Template')
        self.assertEqual(type(tst('')).__qualname__, 'Template')
        # BACKPORT: this shows a different module name than upstream (tstrings vs string.templatelib)
        self.assertEqual(type(tst('')).__module__, 'tstrings')
        a = 'a'
        i = tst('{a}').interpolations[0]
        self.assertEqual(type(i).__name__, 'Interpolation')
        self.assertEqual(type(i).__qualname__, 'Interpolation')
        # BACKPORT: this shows a different module name than upstream (tstrings vs string.templatelib)
        self.assertEqual(type(i).__module__, 'tstrings')

    @unittest.skip("We use dataclasses, which can be subclassed. We need to make them not subclassable.")
    def test_final_types(self):
        with self.assertRaisesRegex(TypeError, 'is not an acceptable base type'):

            class Sub(Template):
                ...
        with self.assertRaisesRegex(TypeError, 'is not an acceptable base type'):

            class Sub(Interpolation):
                ...

    def test_basic_creation(self):
        t = tst('Hello, world')
        self.assertIsInstance(t, Template)
        self.assertTStringEqual(t, ('Hello, world',), ())
        self.assertEqual(fstring(t), 'Hello, world')
        t = tst('')
        self.assertTStringEqual(t, ('',), ())
        self.assertEqual(fstring(t), '')
        t = tst('Hello,\nworld')
        self.assertEqual(t.strings, ('Hello,\nworld',))
        self.assertEqual(len(t.interpolations), 0)
        self.assertEqual(fstring(t), 'Hello,\nworld')

    @unittest.skip("we currently require an expression AND a value for each interpolation, but upstream allows you to just pass one")
    def test_interpolation_creation(self):
        i = Interpolation('Maria', 'name', 'a', 'fmt')
        self.assertInterpolationEqual(i, ('Maria', 'name', 'a', 'fmt'))
        i = Interpolation('Maria', 'name', 'a')
        self.assertInterpolationEqual(i, ('Maria', 'name', 'a'))
        i = Interpolation('Maria', 'name')
        self.assertInterpolationEqual(i, ('Maria', 'name'))
        i = Interpolation('Maria')
        self.assertInterpolationEqual(i, ('Maria',))

    @unittest.skip("we don't support positional __init__ yet")
    def test_creation_interleaving(self):
        t = Template(Interpolation('Maria', 'name', None, ''))
        self.assertTStringEqual(t, ('', ''), [('Maria', 'name')])
        self.assertEqual(fstring(t), 'Maria')
        t = Template(Interpolation('Maria', 'name', None, ''), ' is my name')
        self.assertTStringEqual(t, ('', ' is my name'), [('Maria', 'name')])
        self.assertEqual(fstring(t), 'Maria is my name')
        t = Template('Hello, ', Interpolation('Maria', 'name', None, ''))
        self.assertTStringEqual(t, ('Hello, ', ''), [('Maria', 'name')])
        self.assertEqual(fstring(t), 'Hello, Maria')
        t = Template('Hello', ', ', Interpolation('Maria', 'name', None, ''), '!')
        self.assertTStringEqual(t, ('Hello, ', '!'), [('Maria', 'name')])
        self.assertEqual(fstring(t), 'Hello, Maria!')
        t = Template(Interpolation('Maria', 'name', None, ''), Interpolation('Python', 'language', None, ''))
        self.assertTStringEqual(t, ('', '', ''), [('Maria', 'name'), ('Python', 'language')])
        self.assertEqual(fstring(t), 'MariaPython')

    def test_template_values(self):
        t = tst('Hello, world')
        self.assertEqual(t.values, ())
        name = 'Lys'
        t = tst('Hello, {name}')
        self.assertEqual(t.values, ('Lys',))
        country = 'GR'
        age = 0
        t = tst('Hello, {name}, {age} from {country}')
        self.assertEqual(t.values, ('Lys', 0, 'GR'))

    @unittest.skip("we don't support positional __init__ yet")
    def test_pickle_template(self):
        user = 'test'
        for template in (tst(''), tst('No values'), tst('With inter {user}'), tst('With ! {user!r}'), tst('With format {1 / 0.3:.2f}'), Template(), Template('a'), Template(Interpolation('Nikita', 'name', None, '')), Template('a', Interpolation('Nikita', 'name', 'r', ''))):
            for proto in range(pickle.HIGHEST_PROTOCOL + 1):
                with self.subTest(proto=proto, template=template):
                    pickled = pickle.dumps(template, protocol=proto)
                    unpickled = pickle.loads(pickled)
                    self.assertEqual(unpickled.values, template.values)
                    self.assertEqual(fstring(unpickled), fstring(template))

    def test_pickle_interpolation(self):
        for interpolation in (Interpolation('Nikita', 'name', None, ''), Interpolation('Nikita', 'name', 'r', ''), Interpolation(1 / 3, 'x', None, '.2f')):
            for proto in range(pickle.HIGHEST_PROTOCOL + 1):
                with self.subTest(proto=proto, interpolation=interpolation):
                    pickled = pickle.dumps(interpolation, protocol=proto)
                    unpickled = pickle.loads(pickled)
                    self.assertEqual(unpickled.value, interpolation.value)
                    self.assertEqual(unpickled.expression, interpolation.expression)
                    self.assertEqual(unpickled.conversion, interpolation.conversion)
                    self.assertEqual(unpickled.format_spec, interpolation.format_spec)

class TemplateIterTests(unittest.TestCase):

    def test_abc(self):
        self.assertIsInstance(iter(tst('')), Iterable)
        self.assertIsInstance(iter(tst('')), Iterator)

    def test_final(self):
        TemplateIter = type(iter(tst('')))
        with self.assertRaisesRegex(TypeError, 'is not an acceptable base type'):

            class Sub(TemplateIter):
                ...

    def test_iter(self):
        x = 1
        res = list(iter(tst('abc {x} yz')))
        self.assertEqual(res[0], 'abc ')
        self.assertIsInstance(res[1], Interpolation)
        self.assertEqual(res[1].value, 1)
        self.assertEqual(res[1].expression, 'x')
        self.assertEqual(res[1].conversion, None)
        self.assertEqual(res[1].format_spec, '')
        self.assertEqual(res[2], ' yz')

    def test_exhausted(self):
        template_iter = iter(tst('{1}'))
        self.assertIsInstance(next(template_iter), Interpolation)
        self.assertRaises(StopIteration, next, template_iter)
        self.assertRaises(StopIteration, next, template_iter)

@unittest.skip("we haven't implemented the convert() function yet")
class TestFunctions(unittest.TestCase):

    def test_convert(self):
        from fractions import Fraction
        for obj in ('Café', None, 3.14, Fraction(1, 2)):
            with self.subTest(f'obj={obj!r}'):
                self.assertEqual(convert(obj, None), obj)
                self.assertEqual(convert(obj, 's'), str(obj))
                self.assertEqual(convert(obj, 'r'), repr(obj))
                self.assertEqual(convert(obj, 'a'), ascii(obj))
                with self.assertRaises(ValueError):
                    convert(obj, 'z')
                with self.assertRaises(ValueError):
                    convert(obj, 1)
                with self.assertRaises(ValueError):
                    convert(obj, object())
if __name__ == '__main__':
    unittest.main()
