#!/usr/bin/env python3
"""Fetch and adapt upstream CPython t-string tests for the tstrings backport.

Requires Python 3.14+ (to parse t-string syntax with the ast module).

Usage:
    python scripts/update_upstream_tests.py [--ref REF] [--out-dir DIR]
    or
    uv run --python 3.14 scripts/update_upstream_tests.py [--ref REF] [--out-dir DIR]

Examples:
    python scripts/update_upstream_tests.py
    python scripts/update_upstream_tests.py --ref v3.14.0a1
    python scripts/update_upstream_tests.py --ref 713be70175a2dad477a1cf5e7c00bab0edda04ad
"""  # noqa: E501

from __future__ import annotations

import argparse
import ast
import sys
import textwrap
import urllib.request
from pathlib import Path

RAW_URL = (
    "https://raw.githubusercontent.com/python/cpython"
    "/{ref}/Lib/test/test_string/{filename}"
)
GITHUB_URL = (
    "https://github.com/python/cpython/blob/{ref}/Lib/test/test_string/{filename}"
)
DEFAULT_REF = "main"
DEFAULT_OUT_DIR = Path(__file__).resolve().parent.parent / "tests"
SCRIPT_NAME = "scripts/update_upstream_tests.py"
UPSTREAM_FILES = {
    "_support.py": "_upstream_support.py",
    "test_templatelib.py": "test_upstream_templatelib.py",
}
RESOLVE_REF_URL = "https://api.github.com/repos/python/cpython/commits/{ref}"
TSTRINGS_EXPORTS = {"Template", "Interpolation"}
TSTRINGS_T_ALIAS = "tst"


def resolve_ref(ref: str) -> str:
    """Resolve a symbolic git ref (branch/tag) to a full commit SHA."""
    import json

    url = RESOLVE_REF_URL.format(ref=ref)
    req = urllib.request.Request(url, headers={"Accept": "application/json"})
    with urllib.request.urlopen(req) as resp:
        data = json.loads(resp.read())
    return data["sha"]


def make_header(upstream_name: str, ref: str) -> str:
    url = GITHUB_URL.format(ref=ref, filename=upstream_name)
    return textwrap.dedent(f"""\
        # Adapted from CPython Lib/test/test_string/{upstream_name}
        # Upstream: {url}
        #
        # Auto-generated by {SCRIPT_NAME} — do not edit manually.
        # To regenerate: python {SCRIPT_NAME} --ref {ref}
    """)


class TStringRewriter(ast.NodeTransformer):
    """Rewrite upstream CPython source for the tstrings backport.

    Transforms:
    - from string.templatelib import ... → from tstrings import ...
      (names not exported by tstrings are removed, 't as tst' is added)
    - from test.test_string._support import ... → from _upstream_support import ...
    - t"..." / t'...' literals → tst("...") function calls
    """

    def __init__(self) -> None:
        self.found_tstrings = False
        self.removed_names: list[str] = []

    def visit_ImportFrom(self, node: ast.ImportFrom) -> ast.ImportFrom:
        if node.module == "string.templatelib":
            node.module = "tstrings"
            kept: list[ast.alias] = []
            for alias in node.names:
                if alias.name in TSTRINGS_EXPORTS:
                    kept.append(alias)
                else:
                    self.removed_names.append(alias.name)
            node.names = kept
        elif node.module == "test.test_string._support":
            node.module = "_upstream_support"
        return node

    def visit_TemplateStr(self, node: ast.TemplateStr) -> ast.Call:
        self.found_tstrings = True
        text = self._reconstruct(node)
        return ast.copy_location(
            ast.Call(
                func=ast.Name(id=TSTRINGS_T_ALIAS, ctx=ast.Load()),
                args=[ast.Constant(value=text)],
                keywords=[],
            ),
            node,
        )

    def finalize(self, tree: ast.Module) -> None:
        if self.found_tstrings:
            self._ensure_t_imported(tree)

    def _ensure_t_imported(self, tree: ast.Module) -> None:
        t_alias = ast.alias(name="t", asname=TSTRINGS_T_ALIAS)
        for node in ast.walk(tree):
            if (
                isinstance(node, ast.ImportFrom)
                and node.module == "tstrings"
                and not any(a.name == "t" for a in node.names)
            ):
                node.names.append(t_alias)
                return
        # No existing tstrings import — create one after other imports
        imp = ast.ImportFrom(module="tstrings", names=[t_alias], level=0)
        idx = 0
        for i, stmt in enumerate(tree.body):
            if isinstance(stmt, (ast.Import, ast.ImportFrom)):
                idx = i + 1
        tree.body.insert(idx, imp)

    def _reconstruct(self, node: ast.TemplateStr) -> str:
        parts: list[str] = []
        for child in node.values:
            if isinstance(child, ast.Constant) and isinstance(child.value, str):
                parts.append(child.value.replace("{", "{{").replace("}", "}}"))
            elif isinstance(child, ast.Interpolation):
                expr = ast.unparse(child.value)
                conv = ""
                if child.conversion is not None and child.conversion != -1:
                    conv = f"!{chr(child.conversion)}"
                fmt = ""
                if child.format_spec is not None:
                    fmt = ":" + self._unparse_fmtspec(child.format_spec)
                parts.append("{" + expr + conv + fmt + "}")
        return "".join(parts)

    def _unparse_fmtspec(self, node: ast.expr) -> str:
        if isinstance(node, ast.JoinedStr):
            return "".join(
                str(c.value)
                if isinstance(c, ast.Constant)
                else "{" + ast.unparse(c) + "}"
                for c in node.values
            )
        return ast.unparse(node)


def transform(source: str) -> str:
    tree = ast.parse(source)
    rewriter = TStringRewriter()
    new_tree = rewriter.visit(tree)
    rewriter.finalize(new_tree)
    ast.fix_missing_locations(new_tree)
    result = ast.unparse(new_tree)
    if rewriter.removed_names:
        names = ", ".join(rewriter.removed_names)
        print(f"  Note: removed '{names}' from tstrings import (not in backport)")
    return result


def fetch(url: str) -> str:
    with urllib.request.urlopen(url) as resp:
        return resp.read().decode()


def main() -> None:
    if sys.version_info < (3, 14):
        sys.exit("Error: Python 3.14+ required (for t-string AST support).")
    parser = argparse.ArgumentParser(
        description="Fetch and adapt upstream CPython t-string tests for the tstrings backport.",  # noqa: E501
    )
    parser.add_argument(
        "--ref",
        default=DEFAULT_REF,
        help="Git ref to fetch from (default: %(default)s)",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=DEFAULT_OUT_DIR,
        help="Output directory (default: %(default)s)",
    )
    args = parser.parse_args()
    ref = resolve_ref(args.ref)
    print(f"Resolved {args.ref!r} → {ref}")
    args.out_dir.mkdir(parents=True, exist_ok=True)
    for upstream_name, local_name in UPSTREAM_FILES.items():
        print(f"Fetching {upstream_name} @ {ref} ...")
        url = RAW_URL.format(ref=ref, filename=upstream_name)
        print(f"  URL: {url}")
        source = fetch(url)
        print(f"Rewriting → {local_name} ...")
        transformed = transform(source)
        header = make_header(upstream_name, ref)
        out = args.out_dir / local_name
        out.write_text(header + "\n" + transformed + "\n")
        print(f"  Wrote {out}")
    print("\nDone. You may want to:")
    print("  1. Run 'ruff format' on the output files")
    print("  2. Review and apply any manual adaptations (skip decorators, etc.)")
    print("  3. Run the test suite to verify")


if __name__ == "__main__":
    main()
